### PR TITLE
adaptive_image.module typo fix for 500 internal server error Update README.md with new maintainer.

### LINKED ISSUE #2: PHP Notices on Views Display
When creating a view that is a page where the content is displayed in a teaser mode or when just displaying fields, I get the following notices. None of the default image styles gave me these notices. 

```
Notice: Use of undefined constant pixel_density - assumed 'pixel_density' in /adaptive_image/adaptive_image.module on line 249

Notice: Undefined index: dirname in 
/adaptive_image/adaptive_image.module on line 165
```

### PR DESCRIPTION
**Pull request by drybro**
Add $ prefix to pixel_density so it is recognized as a variable instead of an undefined constant.

Fixes https://github.com/backdrop-contrib/adaptive_image/issues/2

### CODE REVIEW

**Comment by jenlampton** [comment]
oh, oops! I didn't mean to close this. re-opening, and switching target branch.

**Comment by jenlampton** [comment]
It looks like this PR will address the problem reported in https://github.com/backdrop-contrib/adaptive_image/issues/2, so I have linked this PR to that issue using the keyword "Fixes" (so that issue will be marked as closed when this PR is merged).

**Comment by drybro** [comment]
Was hoping closing PR would merge the request. Didn't work.

**Comment by herbdool** [comment]
Merging as part of @backdrop-contrib/bug-squad

**Pull request merged**
